# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a61eeb14d4d9a38c51bd27b90337fc8055963f70afe8643b34d53cf2c3f9fc25a3f65d2a06fc214f8db947320a5956a27683227b6cc56def43ead92dfd117a0d

test:
  secret_key_base: c1582474cc47dd31322ef8742ffcd75995d724a68e578abd0fee973016d7a114db8ec49fab033d1d1649316fea7301b3a77f0d2e9b416aba059bd2916734cb7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
